# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

wso2:
  apk:
    auth:
      enabled: true
      serviceAccountName: wso2apk-platform
      roleName: wso2apk-role
    idp:
      issuer: "https://idp.am.wso2.com/token"
      authorizeEndpoint: "https://idp.am.wso2.com:9095/oauth2/authorize"
      tokenEndpoint: "https://idp.am.wso2.com:9095/oauth2/token"
      revokeEndpoint: "https://idp.am.wso2.com:9095/oauth2/revoke"
      #jwksEndpoint: ""      
      usernameClaim: "sub"
      groupClaim: "groups"
      organizationClaim: "organization"
      clientId: "45f1c5c8-a92e-11ed-afa1-0242ac120002"
      clientSecret: "4fbd62ec-a92e-11ed-afa1-0242ac120002"
    cp:
      enabled: true
      database:
        enabled: true
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://wso2apk-db-service:5432/WSO2AM_DB"
        host: "wso2apk-db-service"
        port: 5432
        databaseName: "WSO2AM_DB"
        username: "wso2carbon"
        password: "wso2carbon"
        validationQuery: "SELECT 1"
        validationTimeout: 250
      devportal:
        appName: "devportal-ds"
        deployment:
          npi: devportal-ds-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/devportal-domain-service:latest
      admin:
        appName: "admin-ds"
        deployment:
          npi: admin-ds-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/admin-domain-service:latest
      backoffice:
        appName: "backoffice-ds"
        deployment:
          npi: backoffice-ds-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/backoffice-domain-service:latest
      devportalUI:
        appName: "devportal-ui"
        deployment:
          npi: devportal-ui-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            path: /
            port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /
            port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 0
          imagePullPolicy: IfNotPresent
          # TODO update image
          image: chanaka3d/portals:linux1.0.0
      managementServer:
        appName: "management-server"
        deployment:
          npi: management-server-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/management-server:latest
      cnpg:
        npi: cnpg-npi
        instances: 1
        clusterName: cluster-example
        appUserPassword: password
        superUserPassword: password
    dp:
      enabled: true
      runtime:
        appName: "runtime-ds"
        deployment:
          npi: runtime-ds-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /health
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/runtime-domain-service:latest
      adapter:
        appName: "adapter"
        deployment:
          npi: adapter-npi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          env:
            ADAPTER_PRIVATE_KEY_PATH: /home/wso2/security/keystore/tls.key
            ADAPTER_PUBLIC_CERT_PATH: /home/wso2/security/keystore/tls.crt
            cp_admin_pwd: admin
            adapter_admin_pwd: admin
          readinessProbe:
            path: /api/am/devportal/v2/apis?limit=2&offset=2
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            path: /api/am/devportal/v2/apis?limit=2&offset=2
            port: 9443
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: Recreate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/adapter:latest
          security:
            sslHostname: "adapter"
      gatewayRuntime:
        appName: "router"
        deployment:
          replicas: 1
          router:
            npi: router-npi
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "1028Mi"
                cpu: "1000m"
            env:
              ROUTER_ADMIN_HOST: 0.0.0.0
              ROUTER_ADMIN_PORT: "9000"
              ROUTER_CLUSTER: default_cluster
              ROUTER_LABEL: Default
              ROUTER_PRIVATE_KEY_PATH: /home/wso2/security/keystore/tls.key
              ROUTER_PUBLIC_CERT_PATH: /home/wso2/security/keystore/tls.crt
              ADAPTER_PORT: "18000"
              ADAPTER_CA_CERT_PATH: /home/wso2/security/truststore/adapter.crt
              ENFORCER_PORT: "8081"
              ENFORCER_ANALYTICS_RECEIVER_PORT: "18090"
              ENFORCER_CA_CERT_PATH: /home/wso2/security/truststore/enforcer.crt
              CONCURRENCY: 2
            readinessProbe:
              path: /api/am/devportal/v2/apis?limit=2&offset=2
              port: 9443
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            livenessProbe:
              path: /api/am/devportal/v2/apis?limit=2&offset=2
              port: 9443
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            strategy: Recreate
            imagePullPolicy: Always
            image: wso2/router:latest
          enforcer:
            npi: enforcer-npi
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "1028Mi"
                cpu: "1000m"
            env:
              ENFORCER_PRIVATE_KEY_PATH: /home/wso2/security/keystore/tls.key
              ENFORCER_PUBLIC_CERT_PATH: /home/wso2/security/keystore/tls.crt
              TRUSTED_CA_CERTS_PATH: /home/wso2/security/truststore
              ADAPTER_XDS_PORT: "18000"
              ENFORCER_LABEL: Default
              ENFORCER_REGION: UNKNOWN
              XDS_MAX_MSG_SIZE: "4194304"
              XDS_MAX_RETRIES: "3"
              apim_admin_pwd: admin
              enforcer_admin_pwd: admin
              tm_admin_pwd: admin
              analytics_authURL: https://localhost:8080
              analytics_authToken:
              JAVA_OPTS: -Dhttpclient.hostnameVerifier=AllowAll -Xms512m -Xmx512m -XX:MaxRAMFraction=2
            readinessProbe:
              path: /api/am/devportal/v2/apis?limit=2&offset=2
              port: 9443
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            livenessProbe:
              path: /api/am/devportal/v2/apis?limit=2&offset=2
              port: 9443
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            strategy: Recreate
            imagePullPolicy: Always
            image: wso2/enforcer:latest
            security:
              sslHostname: "enforcer"

postgresql:
  fullnameOverride: "wso2apk-db-service"
  auth:
    database: WSO2AM_DB
    postgresPassword: wso2carbon
    username: wso2carbon
    password: wso2carbon
  primary:
    extendedConfiguration: |
      max_connections = 400
    initdb:
      scriptsConfigMap: postgres-initdb-scripts-configmap
      user: wso2carbon
      password: wso2carbon
    service:
      ports:
        postgresql: 5432
  image:
    debug: true

idp:
  enabled: true
  database:
    enabled: true
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://wso2apk-db-service:5432/WSO2AM_DB"
    host: "wso2apk-db-service"
    port: 5432
    databaseName: "WSO2AM_DB"
    username: "wso2carbon"
    password: "wso2carbon"
    validationQuery: "SELECT 1"
    validationTimeout: 250
  idpds:
    config:
      issuer: "https://idp.am.wso2.com/token"
      keyId: "gateway_certificate_alias"
      hostname: "idp.am.wso2.com"
      loginPageURl: "https://idp.am.wso2.com:9095/authenticationEndpoint/login"
      loginErrorPageUrl: "https://idp.am.wso2.com:9095/authenticationEndpoint/error"
      loginCallBackURl: "https://idp.am.wso2.com:9095/authenticationEndpoint/login-callback"
    appName: "idp-ds"
    deployment:
      npi: idp-ds-npi
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1028Mi"
          cpu: "1000m"
      readinessProbe:
        path: /health
        port: 9443
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      livenessProbe:
        path: /health
        port: 9443
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      strategy: Recreate
      replicas: 1
      imagePullPolicy: Always
      image: wso2/idp-domain-service:latest
  idpui:
    appName: "idp-ui"
    deployment:
      npi: idp-ui-npi
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1028Mi"
          cpu: "1000m"
      readinessProbe:
        path: /authenticationEndpoint/health
        port: 9443
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      livenessProbe:
        path: /authenticationEndpoint/health
        port: 9443
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      strategy: Recreate
      replicas: 1
      imagePullPolicy: Always
      image: wso2/idp-ui:latest
    configs:
      idpLoginUrl: "https://idp.am.wso2.com:9095/commonauth/login"
      idpAuthCallBackUrl: "https://idp.am.wso2.com:9095/oauth2/auth-callback"