[package]
org = "wso2"
name = "admin_service"
version = "0.0.2-SNAPSHOT"
distribution = "2201.2.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"