# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-gateway-runtime-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.gatewayRuntime.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.enforcer.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.gatewayRuntime.appName ) | indent 8}}
    spec:
      containers:
        - name: enforcer
          image: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.enforcer.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.enforcer.imagePullPolicy }}
          ports:
            - containerPort: 8081
              protocol: "TCP"
            - containerPort: 9001
              protocol: "TCP"
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.gatewayRuntime.deployment.enforcer.resources | indent 10 }}
{{ include "apk-helm.deployment.env" .Values.wso2.apk.dp.gatewayRuntime.deployment.enforcer.env | indent 10 }}
            - name: ADAPTER_HOST_NAME
              value: {{ template "apk-helm.resource.prefix" . }}-adapter-service.{{ .Release.Namespace }}.svc
            - name: ADAPTER_HOST
              value: {{ template "apk-helm.resource.prefix" . }}-adapter-service.{{ .Release.Namespace }}.svc
          volumeMounts:
            - name: enforcer-keystore-secret-volume
              mountPath: /home/wso2/security/keystore/tls.key
              subPath: tls.key
            - name: enforcer-keystore-secret-volume
              mountPath: /home/wso2/security/keystore/tls.crt
              subPath: tls.crt
            - name: enforcer-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/enforcer.crt
              subPath: tls.crt
            - name: adapter-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/adapter.crt
              subPath: tls.crt
            - name: router-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/router.crt
              subPath: tls.crt              
            - name: log-conf-volume
              mountPath: /home/wso2/conf/
            - mountPath: /home/wso2/check_health.sh
              name: enforcer-grpc-probe-script-conf-volume
              subPath: "check_health.sh"
            - name: enforcer-jwt-secret-volume
              mountPath: /home/wso2/security/keystore/mg.pem
              subPath: mg.pem
            - name: enforcer-jwt-secret-volume
              mountPath: /home/wso2/security/truststore/mg.pem
              subPath: mg.pem
            - name: enforcer-jwt-secret-volume
              mountPath: /home/wso2/security/keystore/mg.key
              subPath: mg.key
            - name: enforcer-trusted-certs
              mountPath: /home/wso2/security/truststore/wso2carbon.pem
              subPath: wso2carbon.pem
          # readinessProbe:
          #   exec:
          #     command: [ "sh", "check_health.sh" ]
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
        - name: router
          image: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.router.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.gatewayRuntime.deployment.router.imagePullPolicy }}
          ports:
            - containerPort: 9095
              protocol: "TCP"
            - containerPort: 9090
              protocol: "TCP"
            - containerPort: 9000
              protocol: "TCP"
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.gatewayRuntime.deployment.router.resources | indent 10 }}
{{ include "apk-helm.deployment.env" .Values.wso2.apk.dp.gatewayRuntime.deployment.router.env | indent 10 }}
            - name: ADAPTER_HOST_NAME
              value: {{ template "apk-helm.resource.prefix" . }}-adapter-service.{{ .Release.Namespace }}.svc
            - name: ADAPTER_HOST
              value: {{ template "apk-helm.resource.prefix" . }}-adapter-service.{{ .Release.Namespace }}.svc
            - name: ENFORCER_HOST_NAME
              value: {{ template "apk-helm.resource.prefix" . }}-enforcer-service.{{ .Release.Namespace }}.svc
            - name: ENFORCER_HOST
              value: "127.0.0.1"
          volumeMounts:
            - name: router-keystore-secret-volume
              mountPath: /home/wso2/security/keystore
            - name: router-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/router.crt
              subPath: tls.crt
            - name: adapter-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/adapter.crt
              subPath: tls.crt
            - name: enforcer-truststore-secret-volume
              mountPath: /home/wso2/security/truststore/enforcer.crt
              subPath: tls.crt
            - name: log-conf-volume
              mountPath: /home/wso2/conf/
          # readinessProbe:
          #   httpGet:
          #     port: 9095
          #     path: /ready
          #     scheme: HTTPS
          #     httpHeaders:
          #       - name: Host
          #         value: localhost
          #   periodSeconds: 5
      volumes: 
        - name: enforcer-keystore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-enforcer-server-cert
        - name: enforcer-truststore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-enforcer-server-cert
        - name: log-conf-volume
          configMap: 
            name: {{ template "apk-helm.resource.prefix" . }}-log-conf
        - name: enforcer-grpc-probe-script-conf-volume
          configMap:
            name: {{ template "apk-helm.resource.prefix" . }}-enforcer-grpc-probe-script-conf
            defaultMode: 0777
        - name: router-keystore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-router-server-cert
        - name: router-truststore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-router-server-cert
        - name: adapter-truststore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-adapter-server-cert
        - name: enforcer-jwt-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-enforcer-keystore-secret
        - name: enforcer-trusted-certs
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-enforcer-truststore-secret 
{{- end -}}
