name: Release Backoffice-domain-service.
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Ballerina.
        uses: actions/cache@v3
        id: cache
        with:
          path: "ballerina-dist/*.deb"
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Download Ballerina distribution.
        shell: sh
        run: |
          mkdir -p ballerina-dist
          wget 'https://dist.ballerina.io/downloads/2201.3.0/ballerina-2201.3.0-swan-lake-linux-x64.deb' -P ballerina-dist
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install Ballerina distribution.
        shell: sh
        run: "sudo dpkg -i ballerina-dist/ballerina-2201.3.0-swan-lake-linux-x64.deb"
      - name: Verify Ballerina Version
        shell: sh
        run: "bal -v"
      - name: Set release username and email
        shell: sh
        run: |
          git config --global user.name ${{ secrets.WSO2_BOT_USER }}
          git config --global user.email ${{ secrets.WSO2_BOT_EMAIL }}
      - name: Checkout apk-repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          path: apk-repo
      - name: Run Gradle build
        run: |
          cd apk-repo/backoffice/backoffice-domain-service
          gradle release -Prelease.useAutomaticVersion=true -Pdocker_organization=${{ secrets.DOCKER_ORGANIZATION }} -Pdocker_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_password=${{ secrets.DOCKER_PASSWORD }} -PmultiArch=true
          gradle :ballerina:commit_toml_files
          git push
