name: Release Management Server.
on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: "Release Version"
      next_version:
        type: string
        description: "Next Development Version"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Install Revive
        shell: sh
        run: |
          go install github.com/mgechev/revive@latest

      - name: Checkout apk-repo.
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          path: apk-repo
          token: ${{ secrets.WSO2_BOT_TOKEN }}
      - name: Set release username and email
        shell: sh
        run: |
          git config --global user.name ${{ secrets.WSO2_BOT_USER }}
          git config --global user.email ${{ secrets.WSO2_BOT_EMAIL }}

      - name: Run Gradle build
        run: |
          cd apk-repo/management-server
          gradle release -Prelease.useAutomaticVersion=true -Pdocker_organization=${{ secrets.DOCKER_ORGANIZATION }} -Pdocker_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_password=${{ secrets.DOCKER_PASSWORD }} -Prelease.releaseVersion=${{ github.event.inputs.release_version }} -Prelease.newVersion=${{ github.event.inputs.next_version }} -PmultiArch=true
